### ISSUE TITLE
Sample data

### ISSUE THREAD

**Issue by bdhhtb** [CPearring/lotusnotes-database-converter#1]
Put together a minimal input file, then document what info you want to store/process from that file.

**Comment by cpearring** [comment]
[test input for issue 1.txt](https://github.com/CPearring/lotusnotes-database-converter/files/36210/test.input.for.issue.1.txt)

here's a test file, in the actual txt doc, there are hundreds of these. I took out names for security issues?

In a perfect world, it'd store everything that's listed, for now though, I'm going to start storing the req. date, need date, problem, completedby, status, phone, revisions, and date_created/edited. Everything is in a text file so hopefully it won't be too much of a problem.

**Comment by bdhhtb** [comment]
:+1:
